src/Entity/Specialties.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SpecialtiesRepository")
 */
class Specialties
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $specialty_name;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Doctors", mappedBy="specialty")
     */
    private $doctors;

    public function __construct()
    {
        $this->doctors = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSpecialtyName(): ?string
    {
        return $this->specialty_name;
    }

    public function setSpecialtyName(string $specialty_name): self
    {
        $this->specialty_name = $specialty_name;

        return $this;
    }

    /**
     * @return Collection|Doctors[]
     */
    public function getDoctors(): Collection
    {
        return $this->doctors;
    }

    public function addDoctor(Doctors $doctor): self
    {
        if (!$this->doctors->contains($doctor)) {
            $this->doctors[] = $doctor;
            $doctor->setSpecialty($this);
        }

        return $this;
    }

    public function removeDoctor(Doctors $doctor): self
    {
        if ($this->doctors->contains($doctor)) {
            $this->doctors->removeElement($doctor);
            // set the owning side to null (unless already changed)
            if ($doctor->getSpecialty() === $this) {
                $doctor->setSpecialty(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
        return $this->specialty_name;
    }
}

src/Form/SpecialtiesType.php
<?php

namespace App\Form;

use App\Entity\Specialties;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SpecialtiesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('specialty')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Specialties::class,
        ]);
    }
}

src/Controller/SpecialtiesController.php
<?php

namespace App\Controller;

use App\Entity\Specialties;
use App\Form\Specialties1Type;
use App\Repository\SpecialtiesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/specialties")
 */
class SpecialtiesController extends AbstractController
{
    /**
     * @Route("/", name="specialties_index", methods={"GET"})
     */
    public function index(SpecialtiesRepository $specialtiesRepository): Response
    {
        return $this->render('specialties/index.html.twig', [
            'specialties' => $specialtiesRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="specialties_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $specialty = new Specialties();
        $form = $this->createForm(Specialties1Type::class, $specialty);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($specialty);
            $entityManager->flush();

            return $this->redirectToRoute('specialties_index');
        }

        return $this->render('specialties/new.html.twig', [
            'specialty' => $specialty,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="specialties_show", methods={"GET"})
     */
    public function show(Specialties $specialty): Response
    {
        return $this->render('specialties/show.html.twig', [
            'specialty' => $specialty,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="specialties_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Specialties $specialty): Response
    {
        $form = $this->createForm(Specialties1Type::class, $specialty);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('specialties_index');
        }

        return $this->render('specialties/edit.html.twig', [
            'specialty' => $specialty,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="specialties_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Specialties $specialty): Response
    {
        if ($this->isCsrfTokenValid('delete'.$specialty->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($specialty);
            $entityManager->flush();
        }

        return $this->redirectToRoute('specialties_index');
    }
}

templates/specialties/_delete_form.html.twig
<form method="post" action="{{ path('specialties_delete', {'id': specialty.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ specialty.id) }}">
    <button class="btn">Delete</button>
</form>

templates/specialties/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/specialties/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Specialties{% endblock %}

{% block body %}
    <h1>Edit Specialties</h1>

    {{ include('specialties/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('specialties_index') }}">back to list</a>

    {{ include('specialties/_delete_form.html.twig') }}
{% endblock %}

templates/specialties/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Specialties index{% endblock %}

{% block body %}
    <h1>Specialties index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Specialty_name</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for specialty in specialties %}
            <tr>
                <td>{{ specialty.id }}</td>
                <td>{{ specialty.specialtyName }}</td>
                <td>
                    <a href="{{ path('specialties_show', {'id': specialty.id}) }}">show</a>
                    <a href="{{ path('specialties_edit', {'id': specialty.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('specialties_new') }}">Create new</a>
    <a href="{{path('admin')}}">Back</a>
{% endblock %}

templates/specialties/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Specialties{% endblock %}

{% block body %}
    <h1>Create new Specialties</h1>

    {{ include('specialties/_form.html.twig') }}

    <a href="{{ path('specialties_index') }}">back to list</a>
{% endblock %}

templates/specialties/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Specialties{% endblock %}

{% block body %}
    <h1>Specialties</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ specialty.id }}</td>
            </tr>
            <tr>
                <th>Specialty_name</th>
                <td>{{ specialty.specialtyName }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('specialties_index') }}">back to list</a>

    <a href="{{ path('specialties_edit', {'id': specialty.id}) }}">edit</a>

    {{ include('specialties/_delete_form.html.twig') }}
{% endblock %}