src/Entity/Patients.php
<?php

namespace App\Entity;

use App\Entity\Users;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;


/**
 * @ORM\Entity(repositoryClass="App\Repository\PatientsRepository")
 *
 * Class Patients
 * @package App\Entity
 *
 * @ORM\Table(name="`patients`")
 */
class Patients extends Users
{
    /**
     * @ORM\Column(type="date")
     */
    private $date_of_birth;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="App\Entity\Coupons", mappedBy="patient")
     */
    private $coupons;

    public function __construct()
    {
        $this->coupons = new ArrayCollection();
    }

    public function getDateOfBirth(): ?\DateTimeInterface
    {
        return $this->date_of_birth;
    }

    public function setDateOfBirth(\DateTimeInterface $date_of_birth): self
    {
        $this->date_of_birth = $date_of_birth;

        return $this;
    }

    /**
     * @return Collection|Coupons[]
     */
    public function getCoupons(): Collection
    {
        return $this->coupons;
    }


    public function addCoupon(Coupons $coupon): self
    {
        if (!$this->coupons->contains($coupon)) {
            $this->coupons[] = $coupon;
            $coupon->setPatient($this);
        }

        return $this;
    }


    public function removeCoupon(Coupons $coupon): self
    {
        if ($this->coupons->contains($coupon)) {
            $this->coupons->removeElement($coupon);
            // set the owning side to null (unless already changed)
            if ($coupon->getPatient() === $this) {
                $coupon->setPatient(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->surname;
    }

}

src/Form/PatientsType.php
<?php

namespace App\Form;

use App\Entity\Patients;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PatientsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('surname')
            ->add('date_of_birth')
            ->add('login')
            ->add('password')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Patients::class,
        ]);
    }
}

src/Controller/PatientsController.php
<?php

namespace App\Controller;

use App\Entity\Patients;
use App\Entity\Users;
use App\Form\PatientsType;
use App\Repository\PatientsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/patients")
 */
class PatientsController extends AbstractController
{
    /**
     * @Route("/", name="patients_index", methods={"GET"})
     */
    public function index(PatientsRepository $patientsRepository): Response
    {
        return $this->render('patients/index.html.twig', [
            'patients' => $patientsRepository->findAll(),
        ]);
    }


    /**
     * @Route("/list", name="patients_list", methods={"GET"})
     */
    public function list(PatientsRepository $patientsRepository): Response
    {
        return $this->render('patients/list.html.twig', [
            'patients' => $patientsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="patients_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $patient = new Patients();
        $form = $this->createForm(PatientsType::class, $patient);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $login = $form["login"]->getData();
            $entityRepository = $this->getDoctrine()->getRepository(Users::class);
            $user = $entityRepository->findOneBy([
                'login' => $login
            ]);
            if (!$user)
            {
                $patient->setPassword(sha1($form["password"]->getData()));

                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($patient);
                $entityManager->flush();

                return $this->redirectToRoute('patients_index');
            }


            return $this->redirectToRoute('patients_new');
        }

        return $this->render('patients/new.html.twig', [
            'patient' => $patient,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="patients_show", methods={"GET"})
     */
    public function show(Patients $patient): Response
    {
        return $this->render('patients/show.html.twig', [
            'patient' => $patient,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="patients_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Patients $patient): Response
    {
        $form = $this->createForm(PatientsType::class, $patient);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('patients_index');
        }

        return $this->render('patients/edit.html.twig', [
            'patient' => $patient,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="patients_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Patients $patient): Response
    {
        if ($this->isCsrfTokenValid('delete'.$patient->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($patient);
            $entityManager->flush();
        }

        return $this->redirectToRoute('patients_index');
    }
}

templates/patients/_delete_form.html.twig
<form method="post" action="{{ path('patients_delete', {'id': patient.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ patient.id) }}">
    <button class="btn">Delete</button>
</form>

templates/patients/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/patients/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Patients{% endblock %}

{% block body %}
    <h1>Edit Patients</h1>

    {{ include('patients/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('patients_index') }}">back to list</a>

    {{ include('patients/_delete_form.html.twig') }}
{% endblock %}

templates/patients/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Patients{% endblock %}

{% block body %}
    <h1>Patients</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Surname</th>
                <th>Date_of_birth</th>
                <th>Login</th>
                <th>Password</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for patient in patients %}
            <tr>
                <td>{{ patient.id }}</td>
                <td>{{ patient.name }}</td>
                <td>{{ patient.surname }}</td>
                <td>{{ patient.dateOfBirth ? patient.dateOfBirth|date('Y-m-d') : '' }}</td>
                <td>{{ patient.login }}</td>
                <td>{{ patient.password }}</td>
                <td>
                    <a href="{{ path('patients_show', {'id': patient.id}) }}">show</a>
                    <a href="{{ path('patients_edit', {'id': patient.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('patients_new') }}">Create new</a>
    <a href="{{path('admin')}}">Back</a>
{% endblock %}

templates/patients/list.html.twig
<h3>

    {% for patient in patients %}
        <li>{{ patient.name }}</li>
    {% endfor %}
</h3>

templates/patients/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Patients{% endblock %}

{% block body %}
    <h1>Create new Patients</h1>

    {{ include('patients/_form.html.twig') }}

    <a href="{{ path('patients_index') }}">back to list</a>
{% endblock %}

templates/patients/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Patients{% endblock %}

{% block body %}
    <h1>Patients</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ patient.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ patient.name }}</td>
            </tr>
            <tr>
                <th>Surname</th>
                <td>{{ patient.surname }}</td>
            </tr>
            <tr>
                <th>Date_of_birth</th>
                <td>{{ patient.dateOfBirth ? patient.dateOfBirth|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('patients_index') }}">back to list</a>

    <a href="{{ path('patients_edit', {'id': patient.id}) }}">edit</a>

    {{ include('patients/_delete_form.html.twig') }}
{% endblock %}